@startuml VVS_classes
class Vorsorge {
    address orgaFrom
    uint kundeSV
    struct TransactionDetails
    function changeOrga(adress _orgaFrom, uint _KundeSV, TransactionDetails _transDetails)
    function getInfo(uint _KundeSV)  public view returns(String[])
}
class OrgaChange {
    address orgaTo
    address orgaFrom
    uint kundeSV
    struct TransactionDetails
    function changeOrga(adress _orgaFrom, uint _KundeSV,TransactionDetails _transDetails)
    function selectOrga(address _orgaTo) returns view (address)
}
class Info {
    uint kundeSV
    function getInfo(uint _KundeSV, uint _Zeitspempel) public view returns(infos)
    function searchInfo(uint _Zeitstempel) public view returns(int)
}
class Identifikation {
    uint kundeSV
    function verifyID(uint _KundeSV) public view returns(bool)
}
class Hashing {
    struct TransactionDetails 
    address orgaTo
    address orgaFrom
    uint kundeSV 
    struct infos 
    function hashInfos(struct infos) public view returns(int)
    function dehashInfos(int hash) public view returns(infos)
}
Vorsorge --> OrgaChange : delegatecall
Vorsorge --> Info : delegatecall
OrgaChange --> Identifikation : call
Info --> Identifikation: call
Info --> Hashing: call
OrgaChange --> Hashing: call

@enduml
