@startuml Aktivitätsdiagram getInfo
(*) -->[call] "getBalance() oder getCurrentOrg() in Klasse Vorsorge"
 --> [delegated call]"entsprechende Methode in Klasse Info"
 --> [call] "getVerification()"
 if "ID correct" then 
    --> [true]"start search" as a1
 else 
 ->[false](*)
 endif 
 a1 -->[request] "Server jeweilige Organisation" 
 --> [return] "erfragte Infos"
 -->(*)
@enduml