@startuml Aktivitätsdiagram ChangeOrga 
(*) -->[call] "startOrgaChange() in Klasse Vorsorge"
 --> [delegated call]"startOrgaChange() in Klasse OrgaChange"

 --> [call]"getOrga()"
 --> [call]"finishOrgaChange()" 
 --> [call]"getVerification()" 
 if "ID correct" then 
    --> [true]"return orgaTo" as a1
 else 
 ->[false](*)
endif
 a1 -->[call] "hashInfos"
 --> "write Hash to chain"
 --> "distribute informations" 
 -->(*)
@enduml